services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: llm_port_pii:${LLM_PORT_PII_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rmq:
        condition: service_healthy
    environment:
      LLM_PORT_PII_HOST: 0.0.0.0
      LLM_PORT_PII_DB_HOST: llm_port_pii-db
      LLM_PORT_PII_DB_PORT: 5432
      LLM_PORT_PII_DB_USER: llm_port_pii
      LLM_PORT_PII_DB_PASS: llm_port_pii
      LLM_PORT_PII_DB_BASE: llm_port_pii
      LLM_PORT_PII_RABBIT_HOST: llm_port_pii-rmq
      LLM_PORT_PII_REDIS_HOST: llm_port_pii-redis

  taskiq-worker:
    <<: *main_app
    labels: []
    command:
      - taskiq
      - worker
      - llm_port_pii.tkq:broker

  db:
    image: postgres:16.3-bullseye
    hostname: llm_port_pii-db
    environment:
      POSTGRES_PASSWORD: "llm_port_pii"
      POSTGRES_USER: "llm_port_pii"
      POSTGRES_DB: "llm_port_pii"
    volumes:
      - llm_port_pii-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U llm_port_pii
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: llm_port_pii:${LLM_PORT_PII_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      LLM_PORT_PII_DB_HOST: llm_port_pii-db
      LLM_PORT_PII_DB_PORT: 5432
      LLM_PORT_PII_DB_USER: llm_port_pii
      LLM_PORT_PII_DB_PASS: llm_port_pii
      LLM_PORT_PII_DB_BASE: llm_port_pii
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "llm_port_pii-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  rmq:
    image: rabbitmq:3.9.16-alpine
    hostname: "llm_port_pii-rmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics check_running -q
      interval: 3s
      timeout: 3s
      retries: 50



volumes:
  llm_port_pii-db-data:
    name: llm_port_pii-db-data
