"""RabbitMQ definitions.json generator.

Generates a ``definitions.json`` file that RabbitMQ loads on startup
(via ``load_definitions``).  This creates per-service users with
separate credentials so that the admin/management password is fully
decoupled from the AMQP service accounts.

User layout:
  - ``admin``           — management console, tagged ``administrator``
  - ``llmport-backend`` — backend + worker AMQP access
  - ``llmport-api``     — API gateway AMQP access
  - ``llmport-pii``     — PII module AMQP access (when enabled)
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
from pathlib import Path

# Service user names — hardcoded, not configurable.
SVC_USER_BACKEND = "llmport-backend"
SVC_USER_API = "llmport-api"
SVC_USER_PII = "llmport-pii"


def rabbitmq_password_hash(password: str) -> str:
    """Compute RabbitMQ-compatible SHA-256 password hash.

    Format: ``base64(salt(4) || SHA256(salt || UTF-8(password)))``
    """
    salt = os.urandom(4)
    digest = hashlib.sha256(salt + password.encode("utf-8")).digest()
    return base64.b64encode(salt + digest).decode("ascii")


def _user_entry(name: str, password: str, *, tags: str = "") -> dict:
    return {
        "name": name,
        "password_hash": rabbitmq_password_hash(password),
        "hashing_algorithm": "rabbit_password_hashing_sha256",
        "tags": tags,
    }


def _permission_entry(user: str, vhost: str = "/") -> dict:
    return {
        "user": user,
        "vhost": vhost,
        "configure": ".*",
        "write": ".*",
        "read": ".*",
    }


def generate_definitions(
    *,
    admin_user: str = "admin",
    admin_pass: str,
    backend_pass: str,
    api_pass: str,
    pii_pass: str | None = None,
) -> dict:
    """Build a RabbitMQ definitions dict with per-service users."""
    users = [
        _user_entry(admin_user, admin_pass, tags="administrator"),
        _user_entry(SVC_USER_BACKEND, backend_pass),
        _user_entry(SVC_USER_API, api_pass),
    ]
    permissions = [
        _permission_entry(admin_user),
        _permission_entry(SVC_USER_BACKEND),
        _permission_entry(SVC_USER_API),
    ]
    if pii_pass is not None:
        users.append(_user_entry(SVC_USER_PII, pii_pass))
        permissions.append(_permission_entry(SVC_USER_PII))

    return {
        "users": users,
        "vhosts": [{"name": "/"}],
        "permissions": permissions,
    }


def write_definitions(
    output_dir: Path,
    *,
    admin_user: str = "admin",
    admin_pass: str,
    backend_pass: str,
    api_pass: str,
    pii_pass: str | None = None,
) -> Path:
    """Write ``definitions.json`` into *output_dir*/rabbitmq/.

    Also writes ``10-llmport.conf`` so RabbitMQ loads the definitions
    on startup.  Returns the path to ``definitions.json``.
    """
    rmq_dir = output_dir / "rabbitmq"
    rmq_dir.mkdir(parents=True, exist_ok=True)

    defs = generate_definitions(
        admin_user=admin_user,
        admin_pass=admin_pass,
        backend_pass=backend_pass,
        api_pass=api_pass,
        pii_pass=pii_pass,
    )

    defs_path = rmq_dir / "definitions.json"
    defs_path.write_text(json.dumps(defs, indent=2) + "\n", encoding="utf-8")

    # conf.d snippet that tells RabbitMQ to load our definitions.
    conf_path = rmq_dir / "10-llmport.conf"
    conf_path.write_text(
        "# Auto-generated by llmport deploy — do not edit.\n"
        "load_definitions = /etc/rabbitmq/definitions.json\n",
        encoding="utf-8",
    )

    return defs_path
