"""The installer the operator actually runs, assembled by the backend.

Why this is a generated endpoint rather than a file in the repo: the whole
point of R-1 is that nothing is assembled by the human.  The script that lands
on the node already knows where this backend is, which architecture it is
running on, which agent version to fetch and what that binary should hash to.
None of those are things the operator should have to look up, and a checksum
in particular is the worst possible thing to ask a person to verify by eye --
so the script verifies it instead.

On ``curl | bash``: we deliberately do not.  The neighbouring products pipe a
script from a third-party host straight into a root shell, which is how they
get a one-line install.  Here the script lands on disk first, so it can be
read before it is run, and it verifies what it downloads.  The trust anchor is
"you are talking to your own backend", which the operator is doing anyway --
it is the machine holding all their credentials.

Binary source: the backend serves the binary itself when it has a local copy,
which is what an air-gapped site needs, and otherwise points at the published
release.  Either way the digest the script checks comes from here, so the
verification is identical and the *source* is the only difference.
"""

from __future__ import annotations

import hashlib
import logging
from pathlib import Path

from fastapi import APIRouter, Request
from fastapi.responses import PlainTextResponse, Response

from llm_port_backend.settings import settings

log = logging.getLogger(__name__)

router = APIRouter(prefix="/install", tags=["install"])

#: Agent version this backend expects.  Bumping it here is what makes a fleet
#: converge, because every fresh install reads it from the running backend.
AGENT_VERSION = "0.1.8"

#: Where published binaries live when this backend has no local copy.
RELEASE_URL = (
    "https://github.com/llm-port/llm-port-node-agent/releases/download"
    "/v{version}/llmport-agent-{platform}"
)

#: Platforms we publish, keyed as ``uname -s``/``uname -m`` reports them.
PLATFORMS = {
    "linux-aarch64": "linux-aarch64",
    "linux-arm64": "linux-aarch64",
    "linux-x86_64": "linux-x86_64",
    "linux-amd64": "linux-x86_64",
    "darwin-arm64": "macos-universal",
    "darwin-x86_64": "macos-universal",
}


def _local_binary_dir() -> Path:
    """Where a local copy of the agent binaries would be, if shipped."""
    configured = getattr(settings, "agent_binary_dir", None)
    return Path(configured) if configured else Path("/srv/llm-port/agent-binaries")


def local_binary(platform: str) -> Path | None:
    """The local copy for *platform*, when this deployment carries one."""
    candidate = _local_binary_dir() / f"llmport-agent-{platform}"
    return candidate if candidate.is_file() else None


def binary_digest(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _origin(request: Request) -> str:
    """This backend, as the caller reached it.

    Taken from the request rather than configuration precisely because the
    node has to reach the same address the operator's browser did.  A
    configured value would be right in exactly the deployments that do not
    need this endpoint.
    """
    forwarded_host = request.headers.get("x-forwarded-host")
    forwarded_proto = request.headers.get("x-forwarded-proto")
    if forwarded_host:
        return f"{forwarded_proto or request.url.scheme}://{forwarded_host}"
    return str(request.base_url).rstrip("/")


def render_installer(origin: str) -> str:
    """The POSIX-sh installer, with this deployment's facts already in it."""
    # Written as plain sh, not bash: a DGX OS image is not guaranteed to have
    # anything more, and the script has to run before we have installed
    # anything at all.
    return f"""#!/bin/sh
# LLM.Port node agent installer.
#
# Generated by {origin} for that backend specifically -- the address, the
# agent version and the expected digest are already filled in, so there is
# nothing here for you to look up.
#
# It downloads the agent, checks the digest it was told to expect, installs
# it, and then either asks to join (and waits for someone to approve in the
# browser) or enrolls with a token you passed.
#
# Usage:
#   sh llmport-agent.sh --join [{origin}]
#   sh llmport-agent.sh --backend {origin} --token <token>

set -eu

BACKEND="{origin}"
AGENT_VERSION="{AGENT_VERSION}"
MODE="join"
TOKEN=""
INSTALL_PATH="/usr/local/bin/llmport-agent"

while [ $# -gt 0 ]; do
  case "$1" in
    --join)
      MODE="join"
      if [ $# -gt 1 ] && [ "${{2#--}}" = "$2" ]; then BACKEND="$2"; shift; fi
      ;;
    --backend) BACKEND="$2"; shift ;;
    --token) MODE="token"; TOKEN="$2"; shift ;;
    --install-path) INSTALL_PATH="$2"; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

# -- which build do we need -------------------------------------------------
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
PLATFORM_KEY="${{OS}}-${{ARCH}}"

echo "  Machine:  $PLATFORM_KEY"
echo "  LLM.Port: $BACKEND"
echo

# The backend knows which of its builds fits this machine, and what that build
# should hash to.  Asking it beats making the operator choose.
PLAN=$(curl -fsSL "$BACKEND/api/install/plan?platform=$PLATFORM_KEY") || {{
  echo "ERROR: could not reach $BACKEND" >&2
  exit 1
}}

URL=$(printf '%s' "$PLAN" | sed -n 's/.*"url"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
SHA=$(printf '%s' "$PLAN" | sed -n 's/.*"sha256"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')

if [ -z "$URL" ]; then
  echo "ERROR: this backend publishes no agent build for $PLATFORM_KEY." >&2
  echo "       $PLAN" >&2
  exit 1
fi

# -- fetch and verify -------------------------------------------------------
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

echo "  Downloading the agent..."
curl -fsSL -o "$TMP/llmport-agent" "$URL"

if [ -n "$SHA" ]; then
  echo "  Checking it is the build this backend expects..."
  ACTUAL=$(sha256sum "$TMP/llmport-agent" 2>/dev/null | cut -d' ' -f1) \\
    || ACTUAL=$(shasum -a 256 "$TMP/llmport-agent" | cut -d' ' -f1)
  if [ "$ACTUAL" != "$SHA" ]; then
    echo "ERROR: the download does not match the expected digest." >&2
    echo "       expected $SHA" >&2
    echo "       got      $ACTUAL" >&2
    exit 1
  fi
  echo "  Verified."
else
  # Say so rather than implying a check happened.  A missing digest is a
  # deployment that has not published one, not a passed verification.
  echo "  NOTE: this backend published no digest, so nothing was verified."
fi

# -- install ----------------------------------------------------------------
if [ "$(id -u)" -eq 0 ]; then SUDO=""; else SUDO="sudo"; fi
$SUDO install -m 0755 "$TMP/llmport-agent" "$INSTALL_PATH"
echo "  Installed $INSTALL_PATH"
echo

# -- join or enroll ---------------------------------------------------------
if [ "$MODE" = "token" ]; then
  LLM_PORT_NODE_AGENT_BACKEND_URL="$BACKEND" \\
  LLM_PORT_NODE_AGENT_ENROLLMENT_TOKEN="$TOKEN" \\
    $SUDO -E "$INSTALL_PATH" start
else
  "$INSTALL_PATH" join "$BACKEND"
fi
"""


@router.get("/llmport-agent.sh", response_class=PlainTextResponse)
async def installer_script(request: Request) -> PlainTextResponse:
    """The installer, generated for this backend.

    Unauthenticated: it contains no secret.  Everything it knows is the
    address the caller already reached and which builds exist.
    """
    return PlainTextResponse(
        render_installer(_origin(request)),
        media_type="text/x-shellscript",
        headers={"Content-Disposition": 'attachment; filename="llmport-agent.sh"'},
    )


@router.get("/plan")
async def install_plan(request: Request, platform: str = "linux-x86_64") -> dict[str, str | None]:
    """Where to get the agent for *platform*, and what it should hash to.

    Answering this here is what lets the script stay dumb and the operator
    stay uninvolved: the backend decides between its own copy and the
    published release, and the digest it returns is checked either way.
    """
    build = PLATFORMS.get(platform.strip().lower())
    if build is None:
        return {
            "platform": platform,
            "url": None,
            "sha256": None,
            "reason": f"No agent build is published for {platform}.",
        }

    local = local_binary(build)
    if local is not None:
        # Air-gapped: the node never needs to reach the internet.
        return {
            "platform": build,
            "url": f"{_origin(request)}/api/install/binary/{build}",
            "sha256": binary_digest(local),
            "source": "backend",
        }

    # No local copy, so point at the release.  We do not have its digest
    # without fetching it, and claiming one we have not computed would be
    # worse than saying we have none -- the script prints that plainly.
    return {
        "platform": build,
        "url": RELEASE_URL.format(version=AGENT_VERSION, platform=build),
        "sha256": None,
        "source": "release",
    }


@router.get("/binary/{build}")
async def install_binary(build: str) -> Response:
    """Serve this deployment's own copy of the agent, when it has one."""
    if build not in set(PLATFORMS.values()):
        return Response(status_code=404)
    local = local_binary(build)
    if local is None:
        return Response(status_code=404)
    return Response(
        content=local.read_bytes(),
        media_type="application/octet-stream",
        headers={"Content-Disposition": f'attachment; filename="llmport-agent-{build}"'},
    )
